title: The information hoarder
author: Florence Mary
description: A place to gather my notes on the many topics I get interest in.
theme: just-the-docs

navbar-links:
  Blog: "https://thecodeshewrites.com/"

social-networks-links:
  mastodon: https://hachyderm.io/home
  rss: true

share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false
  reddit: false

title-on-all-pages: true

# For any extra visual customization, you can include additional CSS files in every page on your site. List any custom CSS files here
#site-css:
#  - "/assets/css/custom-styles.css"
# If you have common JavaScript files that should be included in every page, list them here
#site-js:
#  - "/assets/js/custom-script.js"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - docs/
  - .github/

url: https://feliciamarlove.github.io/


aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
